lux-group/lib-types

package.json, types/api/loyalty.d.ts
https://github.com/brandsExclusive/svc-loyalty/pull/143
=> [LENG-1839] Update structure of memberships

package.json, types/api/public-offer.d.ts
=> [KAN-396] Add campaign tag and update package version

types/api/auth.d.ts, types/api/content.d.ts, types/api/order.d.ts, types/api/payment.d.ts, types/api/public-offer.d.ts
Date type was generated by quicktype.io but it's not correct.
=> replace date types with string

types/api/public-offer.d.ts
=> Add package rates to public offer types

.vscode/settings.json, package.json, types/api/bedbank.d.ts, types/api/public-offer-v2.d.ts
* Make FacilityGroups singular - it was a typo to make it plural https://github.com/lux-group/svc-public-offer/pull/766/files#r596415918
* Extract OfferType so that it can be used
=> Fix facility groups

package.json, types/api/bedbank.d.ts, types/api/public-offer-v2.d.ts
https://aussiecommerce.atlassian.net/browse/RES-236
=> [RES-236] Add a fallback image for any missing images on the package tiles for Expedia

types/api/reservation.d.ts
So that I can use them in some data in Public Offer :)
=> Add missing reservation fields

package.json, types/api/public-offer-v2.d.ts, yarn.lock
Supporting the changes in Public Offer - https://github.com/lux-group/svc-public-offer/pull/810
* Add types for "Options"
* Move API query and response interfaces here
=> TBB-105 Types for offer packages / options

types/api/index.d.ts, types/api/public-offer-v2.d.ts, types/api/reservation.d.ts
Adds the missing property fields
=> Add property fields

types/api/public-offer-v2.d.ts, types/api/reservation.d.ts
Adds missing fields as described in TBB-138
=> Add missing fields

types/api/reservation.d.ts
Typing up the tour response from reservation service
=> Add tour types

types/api/geo.d.ts, types/api/public-offer-v2.d.ts, types/api/reservation.d.ts
Some geo data fields are nullable
=> Fix geo data

types/api/reservation.d.ts
=> fix(property): fix the type of `hotel_code`

types/api/public-offer-v2.d.ts
Changes related to https://github.com/lux-group/svc-public-offer/pull/865
=> Change message null to undefined and add GetOffersResponseBody

types/api/public-offer-v2.d.ts
[TBB-111](https://aussiecommerce.atlassian.net/browse/TBB-111): Remove duplicate fields from V2
=> [TBB-111]: Remove duplicated fields

.eslintrc.json, package.json, types/api/offer.d.ts, types/api/reservation.d.ts, yarn.lock
PackageOption, Package, and added id to Surcharges
=> Add some types

package.json, types/api/auth.d.ts
Used to fix https://sentry.io/organizations/luxury-escapes-9m/issues/2473275961/?referrer=slack
=> TBB-268 handle null names

package.json, types/api/reservation.d.ts
@jvke let me know if the interfaces could be named more appropriately.
=> Add response types for POST /api/properties/enquiries

package.json, types/api/public-offer-v2.d.ts
https://aussiecommerce.atlassian.net/browse/SP-662
=> [SP-662] update tour type

package.json, types/api/reservation.d.ts
https://aussiecommerce.atlassian.net/browse/SP-662
=> [SP-662] add logo_id to Tour type

package.json, types/api/reservation.d.ts
https://aussiecommerce.atlassian.net/browse/SP-662
I forgot to make the logo_id type optional.
=> [Sp 662] update tour type

package.json, types/api/public-offer-v2.d.ts
https://aussiecommerce.atlassian.net/browse/SP-662
=> [SP-662] make logo id optional

package.json, tsconfig.json, types/api/offer.d.ts
Related PRs:
https://github.com/lux-group/svc-offer/pull/878
https://github.com/lux-group/svc-order/pull/1756
=> Add max_days_in_future_check_in_is_allowed

package.json, types/api/offer.d.ts, types/api/public-offer-v2.d.ts
Implements types for:
- API.Offer.Badge
- API.PublicOfferV2.Badge
=> [OPX-70] Add typings for badges

types/api/offer.d.ts
=> Remove excessive line

package.json, types/api/public-offer-v2.d.ts, types/api/public-offer.d.ts, types/api/reservation.d.ts
https://aussiecommerce.atlassian.net/browse/CONTB-378
=> feat(connection): add a new flag use_dynamic_occupancy

package.json, types/api/public-offer-v2.d.ts
Jira: https://aussiecommerce.atlassian.net/browse/SP-699
=> add req and res type for map search

package.json
This is regarding this PR - https://github.com/lux-group/lib-types/pull/133
Changed version to publish above changes
=> Changed the version

types/api/bedbank.d.ts
https://github.com/lux-group/svc-public-offer/pull/1048
https://github.com/lux-group/svc-bedbank/pull/650
=> add amenities to bedbankoffer type

package.json
didn't update the version here https://github.com/lux-group/lib-types/pull/136
=> bump version to 1.4.1

package.json, types/api/bedbank.d.ts, types/api/public-offer-v2.d.ts
Changed version from 1.4.3 to 1.4.4.
Added bedBankFlightPrices to the bedbank namespace.
=> Added bedBankFlightPrices interface

package.json, types/api/bedbank.d.ts, types/api/public-offer-v2.d.ts
Changed version to 1.4.5 from 1.4.4
=> Added flight_enabled key to bedbank property type

package.json, types/api/public-offer-v2.d.ts
the previous PR only added it to the svc-bedbank response
=> add amenities to public offer response

package.json, types/api/bedbank.d.ts, types/api/public-offer-v2.d.ts
Changed nearest airport code type to string or null from string.
=> Changed bedbank airport code type as null or string

package.json, types/api/bedbank.d.ts, types/api/public-offer-v2.d.ts
Added new flight key and removed previous separated keys for the flight prices
=> [FLY-342] Added flight key to bed bank offer interface

package.json, types/api/bedbank.d.ts
Added new interface to the bedbank namespace to bedbank properties block list API reposne. (PropertyWithAirport)
=> [FLY-342] Added new interface to bed bank interfaces

package.json, types/api/calendar.d.ts, types/api/index.d.ts, yarn.lock
=> Add calendar service types

package.json, types/api/public-offer-v2.d.ts
E.g. https://test-api.luxuryescapes.com/api/v2/public-offers/0060T00000275OlQAI?region=AU&brand=luxuryescapes
=> To get an offer, only region and brand are required

package.json, types/api/order.d.ts
Add new attributes (tour-related) to `Reservation` interface
=> Add tour details to order-reservation

package.json, types/api/common.d.ts, types/api/flights.d.ts
=> Add SingleCheapestSearchResult

package.json, types/api/experience.d.ts
https://aussiecommerce.atlassian.net/browse/EXP-127
=> [EXP-127] Add Experiences notes

package.json, types/api/index.d.ts, types/api/promo.d.ts
i don't know if this works tbh
=> types for promo svc

package.json, types/api/promo.d.ts
=> fix promo type enum

package.json, types/api/reservation.d.ts
These fields will be used for derbysoft properties.
=> Add channel fields to property

package.json, types/api/search.d.ts
Follow-up to https://github.com/lux-group/lib-types/pull/183.
Related `Public Offer PR`
https://github.com/lux-group/svc-public-offer/pull/1147
=> Update Search and SearchByPlace interfaces

package.json, types/api/bedbank.d.ts
https://aussiecommerce.atlassian.net/browse/CONTB-437
=> feat(tax_registration_number): add collecting and storing PAN

package.json, types/api/experience.d.ts
Add reviews_number and reviews_score fields into Experience type.
=> Add reviews score

package.json, types/api/reservation.d.ts
Adding a missing field onto `RatePlan`
=> [CONTB-429] - Add markup to rate plans

package.json, types/api/common.d.ts, types/api/public-offer-v2.d.ts, types/api/tour.d.ts
=> TOUR-108 Update TourV2Offer data shape

package.json, types/api/bedbank.d.ts, types/api/public-offer-v2.d.ts
https://aussiecommerce.atlassian.net/browse/CONTB-395
=> feat(sales-environment): add package type for check availability

types/api/search.d.ts
Reverts lux-group/lib-types#198
=> Revert "Temp fix place ids"

package.json, types/api/reservation.d.ts
=> Add max occupancy to room rate

package.json, types/api/search.d.ts
Add `optimiseRanking` params introducing in https://github.com/lux-group/svc-search/pull/534 
Merge this after the actual change^.
=> [tbb-574] Add optimise bedbank

package.json, types/api/bedbank.d.ts, types/api/order.d.ts, types/api/public-offer-v2.d.ts
[COVID attributes](https://aussiecommerce.atlassian.net/browse/CONTB-410)
[VAP](https://aussiecommerce.atlassian.net/browse/CONTB-396)
Add new field for customer portal
=> [CONTB-410] Add new fields for frontend

package.json, types/api/order.d.ts
https://aussiecommerce.atlassian.net/jira/software/c/projects/CONTB/boards/90?modal=detail&selectedIssue=CONTB-396
=> [OPEX-394] Add promotions to BedbankItem for order service

package.json, types/api/reservation.d.ts
https://github.com/lux-group/lib-types/pull/new/CONTB-479
Added the conversation of amount of taxes and fees to current region currency
=> feat(taxes_and_fees): add currency of amount

types/api/bedbank.d.ts
Add promotions to `ReservationRoom`. Versions 1.10.17 already released, need to add only code
=> [CONTB-396] add promotions

package.json, types/api/public-offer-v2.d.ts
Jira: https://aussiecommerce.atlassian.net/browse/MP-870
Adds phone to public offer v2 bedbank type.
=> [MP-870] add phone to public offer v2 type

package.json, types/api/reservation.d.ts
https://aussiecommerce.atlassian.net/browse/CONTB-514
=> feat(rate-plans-groups): add types

package.json, types/api/calendar.d.ts
Add api contract for svc-calendar:
https://github.com/lux-group/svc-calendar/pull/168
=> Add calendar lowest prices

package.json, types/api/public-offer-v2.d.ts
Added feature flag for dates requests
=> [OPEX-308] - Dates requests feature flag 

package.json, types/api/tour.d.ts
Public offer needs to use the fullPrice instead of basePrice, so I am going  to include it in the payload here.
Jira - https://aussiecommerce.atlassian.net/browse/TOUR-156
To Do:
=> TOUR-156 Include fullPrice in the tour

package.json, types/api/order.d.ts
[Ticket](https://aussiecommerce.atlassian.net/jira/software/projects/OPEX/boards/106?selectedIssue=OPEX-292)
[Related PR](https://github.com/lux-group/www-le-customer/pull/6465)
We are adding DatesRequest response type for API call in customer portal.
=> [OPEX-292] add DatesRequest response type

package.json, types/api/reservation.d.ts
This reflects what rate type the property supports - AAT/ABT/Both.
=> feat(property): add channel rate type

types/api/public-offer-v2.d.ts, types/api/tour.d.ts
For each itinerary day of a tour, public offer needs to receive
- accommodation
- meals
- locationsVisited
Jira - https://aussiecommerce.atlassian.net/browse/TOUR-179
To Do:
=> Include meals and accommodation in Tour

package.json, types/api/public-offer-v2.d.ts, types/api/reservation.d.ts
https://aussiecommerce.atlassian.net/browse/CONLT-145?atlOrigin=eyJpIjoiMmEwNWVkYTlkMTI0NDk0ZjlhODUyMDZhMWQ4MzA3MWMiLCJwIjoiaiJ9
Also noticing this is quite outdated, I added the rest of cancel policies we support but neglected here.
=> Update cancel policies

package.json, types/api/experience.d.ts, types/api/order.d.ts
Rollback changes until all pieces are done
=> Rollback experiences types

package.json, types/api/public-offer-v2.d.ts, types/api/reservation.d.ts
https://aussiecommerce.atlassian.net/browse/CONTB-474
Add Room Rate Inclusions for `svc-public-offer` and `www-le-customer`
=> [CONTB-474] Add room rate inclusions

types/api/experiences.d.ts
Add new `formData` type for requests received from `sec-experiences`
=> [CRO-251] Add formData type for requesting schema from svc-experiences

package.json
Follow-up to https://github.com/lux-group/lib-types/pull/258
Forgot to update verison
=> [CRO-251] Bump pkg version

package.json, types/api/experiences.d.ts
Minor rename / structure changes
=> [CRO-251] Modify Form Data API response

package.json, types/api/public-offer-v2.d.ts, types/api/tour.d.ts
Tour departures need to know whether they are still for sale or not.
https://aussiecommerce.atlassian.net/browse/TOUR-181
=> TOUR-181 - Add isUnavailable identifier to departure

package.json, types/api/experiences.d.ts
Changing from number (number of minutes) to a string representing the duration ([ISO 8601](https://www.digi.com/resources/documentation/digidocs/90001437-13/reference/r_iso_8601_duration_format.htm))
=> Updade period type

package.json, types/api/experiences.d.ts
JIRA: [EXP-345](https://aussiecommerce.atlassian.net/jira/software/projects/EXP/boards/95?selectedIssue=EXP-345)
=> [EXP-345]: added parent in experience category

package.json, types/api/experiences.d.ts
=> fix applicable_until case

package.json, types/api/reservation.d.ts
https://aussiecommerce.atlassian.net/browse/CONTB-561
=> feat(inclusions): update units

package.json, types/api/public-offer-v2.d.ts
https://aussiecommerce.atlassian.net/browse/CONTB-556
Push `No Inclusions` field for `svc-public-offer`
=> [CONT-556] Add no inclusions

package.json, types/api/experiences.d.ts
Self-explanatory.
I'm going to merge this 1-liner without review.
=> add type field to Experience tickets

package.json, types/api/reservation.d.ts
Adds additional_tax field to TaxesAndFees
=> feat(taxes) add additional_tax boolean to taxes

package.json, types/api/experiences.d.ts
add api schema for availability enquiry endpoint
=> add experience availability enquiry

package.json, types/api/reservation.d.ts
Adds a taxes_payable_at_property field to Property so we can flag different display logic for properties that have taxes to pay at the hotel
=> feat(taxes) add taxes_payable_at_property to Property

package.json, types/api/reservation.d.ts
https://aussiecommerce.atlassian.net/browse/CONLT-187?atlOrigin=eyJpIjoiNmUyZWVjMjljNTg2NGRkMTljNjYzMWY4ZWEzODJiYTQiLCJwIjoiaiJ9
Add a flag to indicate if we've mapped our own property id to iceportal properties.
=> feat(property): add iceportal mapped flag

package.json, types/api/reservation.d.ts
Giving it a rethink I prefer these two required fields but can be null sometimes as we will be always presenting them from reservation svc.
=> feat(hotel-meta): update meta fields type

package.json, types/api/experiences.d.ts
JIRA: [EXP-390](https://aussiecommerce.atlassian.net/jira/software/projects/EXP/boards/95?assignee=617fca5a327da4006980ee1e&selectedIssue=EXP-390)
Update experience contract and lib-types with the new Experience Item interface
The new interface is documented in confluence page: [What should the new experience_item look like](https://aussiecommerce.atlassian.net/wiki/spaces/PE/pages/2225733726/What+should+the+new+experience+item+look+like)
=> EXP-390: update experience item attrs

package.json, types/api/order.d.ts
- removed sale_price;
- added new Ticket attrs;
- changed status type.
=> [NO-JIRA]: update Order interface in Experience Item

.gitignore, package.json, types/api/reservation.d.ts
https://aussiecommerce.atlassian.net/browse/CONLT-212
Added `productType` to RoomRates
=> feat(rooms): added product type to room rates

package.json, types/api/public-offer-v2.d.ts
Ticket
https://aussiecommerce.atlassian.net/browse/CONTB-576
=> [CONTB-576] Add bonus inclusions tag on the offer page when the room rate inclusions have LOS set

types/api/tour.d.ts
=> Deprecate tour types

package.json, types/api/public-offer-v2.d.ts, types/api/reservation.d.ts
https://aussiecommerce.atlassian.net/browse/CONTB-607
Add Rate plans regions for public-offer
=> [CONTB-605] Add Rate plan regions

package.json, types/api/search/hotel.d.ts
- add `searchType` parameter
- add sort by distance parameter
=> Add search type

package.json, types/api/search/hotel.d.ts
add a missing search type "map area"
=> add search type "map area"

package.json, types/api/offer.d.ts, types/api/search/hotel.d.ts
Add types for "offer content" and a new optional param "applyFrontPage" in search
=> Search add front page sort

package.json, types/api/search/hotel.d.ts
https://aussiecommerce.atlassian.net/browse/USZ-15
=> added property type and category to search params

package.json, types/api/search/hotel.d.ts
https://aussiecommerce.atlassian.net/browse/USZ-15
Also made them type string to accomodate comma separated lists of search items
=> [USZ-15] feat(typecategory): modified these params to be plurals

package.json, types/api/index.d.ts, types/api/referral.d.ts, yarn.lock
- Add new Referral object
- bump @typescript-eslint/eslint-plugin version
=> Engx 330 new referral object types

package.json, types/api/referral.d.ts
-Make status a number
-Add payload to redemption response
=> Engx 330 fix status type

package.json, types/api/referral.d.ts
- Add lib-types for Referee Value 
- Add Generic APIResponse
=> Add generic API response + RefereeValue

package.json, types/api/order.d.ts
Just add this attrs for LED experiences:
- redemption_location_id
- redemption_location_name
=> EXP-520: add redemption_location to order experience item

package.json, types/api/tour.d.ts
Related PRs:
https://github.com/lux-group/svc-tour/pull/224
https://github.com/lux-group/svc-tour/pull/223
https://github.com/lux-group/www-le-admin/pull/2429
=> [TOUR-463] add rankings to tours

types/api/search/hotel.d.ts
https://aussiecommerce.atlassian.net/browse/OSS-168
Add new fields introduced in: https://github.com/lux-group/svc-search/pull/951
=> [oss-168] Add available flag

package.json, types/api/flights.d.ts
Add optional errors object for AirportsResult
=> FLY-1709 Add optional errors property for airport result

package.json, types/api/public-offer-v2.d.ts
We need to add some attributes to Badges type to allow for scheduling.
https://github.com/lux-group/svc-offer/pull/1094
https://github.com/lux-group/svc-public-offer/pull/1608
=> [OPEX-826] update Badge types for account of schedules

package.json, types/api/offer.d.ts, types/api/public-offer-v2.d.ts
Additions to this https://github.com/lux-group/lib-types/pull/345
=> [OPEX-826] fix all badge types

package.json, types/api/reservation.d.ts
https://aussiecommerce.atlassian.net/browse/CONLT-596
Add new optional field 'is_base_rate' to the RatePlan interface.
=> [CONLT-596] Add is_base_rate to rateplan

package.json, types/api/experiences.d.ts
https://aussiecommerce.atlassian.net/browse/EXP-2029
Removing musement as it is no longer used.
=> [EXP-2029] [REMOVE-MUSEMENT] remove musement experiences types

package.json, types/api/order.d.ts
Related PR: https://github.com/lux-group/www-le-admin/pull/4143
=> [CRUZ-1562]: creating CruiseItem interface

package.json, types/api/reservation.d.ts
add `chain_id` to reservation property
=> feat(CONTB-1525): add chain_id to property

.circleci/config.yml, package.json
Add access=restricted to NPM publish
=> Ex 2197 make repo private
