- types/api/public-offer-v2.d.ts
Turns out you can't use enums in declaration files.
https://lukasbehal.com/2017-05-22-enums-in-declaration-files/
Makes sense since an enum is more than a type, it can be used at runtime, hence has to go in a .ts file.
Not sure of the best way to do this, so have opted for a union type for now, and we can figure out how to support enums through this module separately.
> Use union type instead of enum for OfferType

- types/api/public-offer-v2.d.ts
* Options served via the API might not have a price - the frontend interprets this as "Sold out"
* Add a couple of missing property fields. More to come as part of separate PR
> Make price optional

- package.json
- types/api/order.d.ts
[Ticket](https://aussiecommerce.atlassian.net/browse/KAN-1150?atlOrigin=eyJpIjoiOTNlY2ZlYzI5YTljNGRlY2I2YzRiOTk3MzU3MTk2NTIiLCJwIjoiaiJ9)
Add types for refunds api call: `/api/orders/_orderId_/refunds.`
> KAN-1150 add types for refunds

- types/api/public-offer-v2.d.ts
As discovered in the test environment. Should the other schedules be optional too?
> listVisibility is not guaranteed to be there

- types/api/public-offer-v2.d.ts
- types/api/reservation.d.ts
As requested by Robert:
this should be calculated on the front end as prices may affected by factors out of public offers control OR it should be the rate plan discount (e.g. for last minute escapes)- of which we have the rate plan, so no need to duplicate the field.
Add the discount percent to the rate plan
> Remove discount from option

- types/api/reservation.d.ts
Reviews can be undefined for both property and tour (when reviews_count === 0).
> Reviews can be undefined

- types/api/public-offer-v2.d.ts
To prove it:
```
$ curl https://api.luxuryescapes.com/api/v2/public-offers/list | jq
{
"status": 400,
"message": "Invalid url query parameters",
"errors": [
{
"path": "offerType",
"message": "should be a valid enum value"
},
{
"path": "placeIds",
"message": "Place ids is required"
},
{
"path": "region",
"message": "should be a string"
},
{
"path": "brand",
"message": "should be a string"
}
]
}
```
> public-offers/list required params

- types/api/public-offer-v2.d.ts
We need to keep the metaDescription and attractions fields outside of the copy in BedbankOffer. This solution is only temporal, to have time to change all the dependencies
> [TBB-111]: add back metaDescription and attractions fields in BedbankOffer

- types/api/public-offer-v2.d.ts
Without this, `LeHotelOfferType` and `LeTourOfferType` will include the bedbank offer type! Spotted while reviewing https://github.com/lux-group/www-le-customer/pull/5177/files
> Fix Offers and types

- types/api/public-offer-v2.d.ts
Turns out that a package `copy.description` is actually a description of the **inclusions**.
Also, the existing `inclusions.description` field is actually the `highlights` field (often smaller than description), which is optionally there
> Update v2 package inclusions format

- types/api/offer.d.ts
- types/api/public-offer-v2.d.ts
Public offer images can have have a title set on them, it's used as the alt and in some cases a caption.
> Add title to Public Offer images

- .circleci/config.yml
- package.json
So that we can publish from CircleCI
Follows the same patterns as lib-global and http-auth-client
> Auto publish tags

- package.json
- types/api/public-offer-v2.d.ts
[OPEX-125](https://aussiecommerce.atlassian.net/browse/OPEX-125)
An optional `heading` field for an offer inclusions
> [OPEX-125] add heading field to offer inclusions

- package.json
- types/api/public-offer.d.ts
[OPEX-126](https://aussiecommerce.atlassian.net/browse/OPEX-126)
Adding new `offer_inclusions_heading`, `offer_inclusions_long`, `offer_inclusions_short` fields to the Public Offer
> [OPEX-126] add offer inclusions fields

- package.json
https://github.com/lux-group/lib-types/pull/140 1.4.5 was already taken so it failed
> bump to 1.4.6

- package.json
- types/api/offer.d.ts
- svc-search needs schedule `brand` to flat schedules for all brands and regions.
- Algolia needs `holiday_types` to search by holiday types.
> Add offer fields

- package.json
- types/api/reservation.d.ts
It's required by ratedock. We had these fields long time ago so don't think adding these will break anything.
> feat(rate-plan): add fields to rate plan

- package.json
- types/api/public-offer.d.ts
Fix incorrect property names in V1 offer:
- `bundledWithFlightsOnly` to `bundled_with_flights_only`
- `whitelistedCarrierCodes` to `whitelisted_carrier_codes`
> Fix incorrect property names in V1 offer

- package.json
This PR only updates the version as the last changes failed because package.json was not updated before.
> EXP-169: update version to 1.10.11

- package.json
- types/api/public-offer-v2.d.ts
- types/api/tour.d.ts
- Adding Departure and Price data to what svc-tour will provide
- Small changes to the data in svc-public-tour response
Related PRs
https://github.com/lux-group/svc-public-offer/pull/1179
https://github.com/lux-group/svc-tour/pull/51
> TOUR-101: Add departures and purchasable options

- package.json
- types/api/reservation.d.ts
DS requires a relevant field that we should indicate if it's a pay now or pay later. We'll need this field in DS svc ts file so rate plan doesn't complain not having this field.
> feat(reservation): add should instant purchase flag to rate plan

- package.json
- types/api/tour.d.ts
I had incorrectly defined the season interface in the previous PR; it had `startPlace` and `endPlace` instead of `startLocation` and `endLocation`, which did not match what we want to present in `svc-tour`
> fix season interface

- package.json
- types/api/public-offer-v2.d.ts
- types/api/tour.d.ts
In https://github.com/lux-group/svc-public-offer/pull/1261#issuecomment-1028470078 , we were requested to preserve `brand`, and introduce another object that contains brand data.
> preserve brand string, introduce brandObjet

- package.json
- types/api/experiences.d.ts
Just added a few fields that are displayed in the new Experiences UI
Brother PR: https://github.com/lux-group/svc-connection-musement/pull/30
> [EXP-249] add requested fields

- package.json
- types/api/public-offer-v2.d.ts
- types/api/reservation.d.ts
[Ticket](https://aussiecommerce.atlassian.net/jira/software/projects/OPEX/boards/106?selectedIssue=OPEX-387)
[www-le-admin](https://github.com/lux-group/www-le-admin/pull/2047)
[svc-reservation](https://github.com/lux-group/svc-reservation/pull/1334)
[svc-reporting](https://github.com/lux-group/svc-reporting/pull/1359)
We are adding new cancellation policy - parnter policy, first 7 days will be allowed to refund to origin or credits 8-21 days refund to credits, > 21 days non-refundable.
> [OPEX-387] add new cancellation policy, partner policy

- package.json
- types/api/search/experience.d.ts
- types/api/search/index.d.ts
Experience available dates don't mean to have a "check in" and "check out", because it 's not searching an experience last all through the dates.
Chat: https://luxgroup-hq.slack.com/archives/C01TFQ0QS0Y/p1645419879139389
> Change available dates var name

- package.json
- types/api/public-offer-v2.d.ts
- types/api/public-offer.d.ts
Adds the @deprecated tag to the public-offer types.
This will inform consumers of the API to switch over to the contract version being published via `@luxuryescapes/contract-public-offer`
Bumped the version to 1.13.0 as seems a pretty major (but minor?) change to deprecate whole apis
> Deprecate public offer types from lib-types

- package.json
- types/api/experiences.d.ts
Looking forward to a workflow that doesn't involve bumping lib-types version every time we add an API field.
In the meantime, I'll merge this 1-liner without review.
> add field to Experiences Offers

- package.json
- types/api/public-offer-v2.d.ts
https://aussiecommerce.atlassian.net/browse/CONTB-559
Change made because Robert proposed renaming this field.
https://github.com/lux-group/svc-public-offer/pull/1274
Add `isPartnerProperty` instead of `noInclusions` field for offer.
> [CONTB-559] Add `isPartnerProperty` instead of `noInclusions`

- package.json
- types/api/experience.d.ts
- types/api/experiences.d.ts
- types/api/order.d.ts
Jira: [EXP-382](https://aussiecommerce.atlassian.net/jira/software/projects/EXP/boards/95?assignee=617fca5a327da4006980ee1e&selectedIssue=EXP-382)
[svc-experiences](https://github.com/lux-group/svc-experiences/pull/82)
The activity consists of creating a directory for experience service contracts. For this, a contract was created based on the `experiences.d.ts` file of the [LIB-TYPES](https://github.com/lux-group/lib-types/blob/master/types/api/experiences.d.ts) project.
A new independent directory has been created within `src/contract` to maintain experience contracts
> EXP-382: create a contract for experiences (contract-svc-experiences)

- types/api/reservation.d.ts
https://github.com/lux-group/svc-reservation/pull/1373
We moved reservation types into contract-svc-reservation, so we deprecating reservation types in this lib.
> [OPEX] deprecate reservation types in favor of contract-svc-reservation

- package.json
- types/api/discovery.d.ts
[Ticket](https://aussiecommerce.atlassian.net/jira/software/projects/OPEX/boards/106?selectedIssue=OPEX-310)
https://github.com/lux-group/lib-regions/pull/212
https://github.com/lux-group/lib-uri-templates/pull/151
https://github.com/lux-group/svc-discovery/pull/252
https://github.com/lux-group/svc-graphql/pull/193
We are providing priority phone numbers for high value orders, I'm adding those similar to regions array but in a separate module to exclude any issues. I declared new api endpoint in lib-uri-templates it will be used by svc-discovery to serve data for svc-graphql.
> [OPEX-310] add PriorityPhoneNumber types for svc-graphql

- package.json
- types/api/bedbank.d.ts
- types/api/public-offer-v2.d.ts
https://aussiecommerce.atlassian.net/browse/CONLT-175?atlOrigin=eyJpIjoiNGUzYjc5ZmY1ZDIzNDNlZDkyMzJmNjBiYjI5NWJkZTAiLCJwIjoiaiJ9
the api upgrade pr is https://github.com/lux-group/svc-bedbank/pull/1050
Thinking I'll make it optional instead of removing those for now given clients like public offer svc are using objectWithOnly, so I'll keep these as optional there just in case
> Make two fields optional due to api upgrade

- package.json
- types/api/order.d.ts
##Description
Needs to add experience provider to admin portal
[www-le-admin](https://github.com/lux-group/www-le-admin/pull/2257)
[svc-order](https://github.com/lux-group/svc-order/pull/2135)
> EXP-610: add provider to order experience item

- package.json
- types/api/order.d.ts
We need to add status_reason to filter out cancelled insurances due to them being upgraded.
> [OPEX-578] insurance type update, add status_reason

- package.json
- types/api/referral.d.ts
Add new, simpler, status types
Note: total_amount_redeemed is currently being returned as a number and lib-types is being updated to reflect that
Required for: 
- https://github.com/lux-group/svc-promo/pull/315
- https://github.com/lux-group/www-le-customer/pull/7880
> Add new status types

- package.json
- types/api/referral.d.ts
Avoid breaking API changes through restoring the orignal types & API Response shape
Paired with: 
https://github.com/lux-group/svc-promo/pull/315
> MP-1050-Make-API-Changes-non-breaking

- package.json
- types/api/referral.d.ts
- To better track how changes to referral configuration is impacting the rate of referrals, include current 'Referral GTM params' in the existing GetReferralCodeById API response
- Type the (existing) getCodeByUserId response
> Mp 1141 add google tracking params

- types/api/payment.d.ts
This represents the response json payload from taking a payment - and it may come from various different providers (Stripe, paypal, klarna, etc) so the response shape can vary a lot between providers, and even within one provider (depending on if the payment passed or failed etc).
And, the response json can have nested objects. So, the current type doesn't work.
This has come up as a problem in the context of this pr / commit: https://github.com/lux-group/www-le-admin/pull/5628/commits/f95314914928f0a308d93320f4f1a82d5217295d
> make response json flexible
